CREATE TABLE IF NOT EXISTS OtherLeagueSeason
(  PLAYER_ID    INTEGER NOT NULL,
   SEASON_ID    INTEGER NOT NULL,
   LEAGUE       TEXT    NOT NULL,
   POSITION     TEXT    NOT NULL,
   AGE          REAL    NOT NULL,
   GAMES_PLAYED INTEGER,
   GOALS        INTEGER,
   ASSISTS      INTEGER,
   POINTS       INTEGER,
   G_PACE       REAL,
   A_PACE       REAL,
   PRIMARY KEY ( PLAYER_ID, SEASON_ID, LEAGUE ) );
