CREATE TABLE IF NOT EXISTS RosterSkater
(  PLAYER_ID   INTEGER NOT NULL PRIMARY KEY,
   PLAYER_NAME TEXT    NOT NULL,
   POSITION    TEXT,
   TEAM        TEXT );

CREATE INDEX IF NOT EXISTS RosterSkaterNameIndex
   ON RosterSkater ( PLAYER_NAME );
