ALTER TABLE SkaterSeason ADD COLUMN PLAYOFF_GAMES INTEGER NOT NULL DEFAULT 0;
ALTER TABLE SkaterSeason ADD COLUMN PLAYOFF_GOALS INTEGER NOT NULL DEFAULT 0;
ALTER TABLE SkaterSeason ADD COLUMN PLAYOFF_ASSISTS INTEGER NOT NULL DEFAULT 0;
